language: java
before_install:
- chmod +x gradlew
- ./gradlew --refresh-dependencies
cache:
  directories:
  - $HOME/.gradle
jdk:
- oraclejdk8
notifications:
  slack:
    on_success: never
    on_failure: never