name: @name@
main: @mainPackage@.@name@
version: @version@
api-version: @apiVersion@
description: @description@
author: @author@
website: @website@
softdepend: [PlaceholderAPI]
commands:
  ibooks:
    description: Command to manage books
    permission: interactivebooks.command
    aliases: [interactivebooks, ib]