name: InteractiveBooks
main: net.leonardo_dgs.interactivebooks.InteractiveBooks
version: @version@
api-version: 1.13
description: @description@
softdepend: [PlaceholderAPI]
commands:
  ibooks:
    description: Command to manage books
    permission: interactivebooks.command
    aliases: [interactivebooks, ib]