name: InteractiveBooks
main: net.leomixer17.interactivebooks.InteractiveBooks
version: @version@
api-version: 1.13
description: @description@
softdepend: [PlaceholderAPI]
commands:
  ibooks:
    description: Command to manage books
    aliases: [interactivebooks, ib]